id: P000680
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-16 16:36:44.173236
source_metadata:
  id: bdr:W1KG14545
  title: ཧ་རུའེ་ཕོད་ཐར་དང་གསང་བའི་ཁང་པ།
  author: ''
  volumes:
    e05965bf074c4699a116458c8bf90d23:
      image_group_id: I1KG15696
      title: ''
      volume_number: 1
      total_pages: 366
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
