id: IB65E0BB5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T15:49:16+00:00'
last_modified: '2022-06-07T12:38:49.678289+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14545
  title: ཧ་རུའེ་ཕོད་ཐར་དང་གསང་བའི་ཁང་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    0BAD:
      image_group_id: I1KG15696
      title: ''
      total_pages: 366
      order: 1
      base_file: 0BAD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
